# Generated by Django 4.2.7 on 2023-11-06 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("info_scape_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Autor",
            new_name="Author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
    ]
