# Generated by Django 4.2.7 on 2023-11-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("info_scape_app", "0002_rename_autor_author_remove_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="info_scape_app.author",
                verbose_name="",
            ),
        ),
    ]
