# Generated by Django 4.2.7 on 2023-11-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info_scape_app", "0005_alter_post_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="name",
        ),
        migrations.AddField(
            model_name="author",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="author",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(to="info_scape_app.tag"),
        ),
    ]
