# Generated by Django 4.2.7 on 2023-11-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info_scape_app", "0006_remove_author_name_author_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="bio",
            field=models.TextField(max_length=2000),
        ),
    ]
