# Generated by Django 4.2.7 on 2023-11-06 16:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("info_scape_app", "0007_alter_author_bio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="image",
            new_name="image_name",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="name",
            new_name="caption",
        ),
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="tag",
        ),
        migrations.AddField(
            model_name="author",
            name="email_address",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="image_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="info_scape_app.tag"),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="info_scape_app.author",
                verbose_name="",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MinValueValidator(20)]
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
