# Generated by Django 4.2.7 on 2023-11-06 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("info_scape_app", "0008_rename_image_author_image_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
    ]
